title: OSM Scout Server
description: Maps server providing tiles, geocoder, and router<br><small><small><a href='https://rinigus.github.io/osmscout-server/en'>English</a> <a href='https://rinigus.github.io/osmscout-server/es'>español</a> <a href='https://rinigus.github.io/osmscout-server/fr'>français</a></small></small> <a href='https://rinigus.github.io/osmscout-server/sv'>svenska</a></small></small>
show_downloads: false
theme: jekyll-theme-slate
