title: OSM Scout Server
description: Maps server providing tiles, geocoder, and router<br><small><small><a href='https://rinigus.github.io/osmscout-server/en'>English</a> <a href='https://rinigus.github.io/osmscout-server/fr'>Français</a></small></small>
show_downloads: false
theme: jekyll-theme-slate